//Profile
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_PROFILE_IMAGE = 'GET_PROFILE_IMAGE';

export const GET_USER_DETAILS_HEADER = 'GET_USER_DETAILS_HEADER';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';

export const CREATE_MOMENT = 'CREATE_MOMENT';
export const GET_USER_MOMENTS = 'GET_USER_MOMENTS';
export const CLEAR_USER_MOMENTS = 'CLEAR_USER_MOMENTS';
export const DELETE_USER_MOMENTS = 'DELETE_USER_MOMENTS';
export const UPDATE_USER_MOMENTS = 'UPDATE_USER_MOMENTS';
export const GET_USER_SEARCH_RESULT = 'GET_USER_SEARCH_RESULT';

export const CREATE_MEMORY = 'CREATE_MEMORY';
export const GET_MEMORIES = 'GET_MEMORIES';

export const FETCH_USER = 'FETCH_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ERROR = 'GET_ERROR';

export const SHOW_LOGIN_PANEL = 'SHOW_LOGIN_PANEL';
export const SHOW_REGISTER_PANEL = 'SHOW_REGISTER_PANEL';
export const CLOSE_LOGIN_REGISTER_PANEL = 'CLOSE_LOGIN_REGISTER_PANEL';

export const GET_RELATIONSHIP_STATUS = 'GET_RELATIONSHIP_STATUS';

//UI
export const DROPDOWN_SELECTED_ON_MOMENT_IN_TIMELINE = 'DROPDOWN_SELECTED_ON_MOMENT_IN_TIMELINE';

export const LOAD_MEMORY_LANE = "LOAD_MEMORY_LANE";